name: Code formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8 isort mypy
    - name: Format
      run: black --check ./src/resample
    - name: Lint
      run: flake8 ./src/resample
    - name: Check imports
      run: isort --recursive --check-only ./src/resample
    - name: Type check
      run: mypy ./src/resample
