name: Publish Test PyPI

on:
  push:
    branches: [master, publish-to-pypi]

jobs:
  build-and-publish:
    name: Build and publish to Test PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install pep517
      run: |
        python -m pip install pep517 --user
    - name: Build a binary wheel and a source tarball
      run: |
        python -m pep517.build --source --binary --out-dir dist/ .
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_token }}
        repository_url: https://test.pypi.org/legacy/
